site_name: DolARK

theme:
    name: mkdocs

nav:
    - Home: index.md
    - Single Agent: single_agent.md
    - Equilibrium: equilibrium.md
    - Perturbation: perturbation.md
    - Krussell-Smith: krussell_smith.md
    - Shocks: shocks.md

markdown_extensions:
  - mdx_math
  - markdown.extensions.admonition
  - pymdownx.arithmatex
  - pymdownx.highlight:
      use_pygments: true
      extend_pygments_lang: [yaml]
  - pymdownx.superfences

extra_css:
    - css/extra.css

extra_javascript:
  # other extra java script
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@3
  - https://cdn.jsdelivr.net/npm/vega-embed@5
